---
targets:
  - name: target1
    address: http://localhost:8080
    labels:
      label1: value1
      label2: value2
  - name: target2
    address: http://localhost:8081
    labels:
      label1: value1
      label3: value3
