---
port: 9981
insecure: false
interval: 5
targets:
  - type: rest
    url: http://example.com/api
    method: GET
    headers: {}
    parser_rules: {}
    timeout: 30
    retry_count: 3
    retry_interval: 1
  - type: file
    file_path: /path/to/local/file.json
    file_format: json
